name: chimera-break
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - pysam>=0.19.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pyyaml>=6.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pip
  - pip:
    - -e .